### ISSUE TITLE
JaCoCo code coverage

### ISSUE THREAD

**Issue by deritamas** [biharygergo/outlay#17]

**Comment by deritamas** [comment]
1a337d932c6fd0c2efdb7913123921c172c0f682

**Comment by deritamas** [comment]
Wiki page for this issue:
https://github.com/biharygergo/outlay/wiki/Using-JaCoCo-to-test-code-coverage

**Comment by deritamas** [comment]
@davidka95 review it please!

**Comment by davidka95** [comment]
Well done!
