### ISSUE TITLE
Add continuous integration to project

### ISSUE THREAD

**Issue by biharygergo** [biharygergo/outlay#5]
This would be a great thing to have!

**Comment by biharygergo** [comment]
1cbbfaebcbb7b95949d5b4003771b917fb97de6e

**Comment by biharygergo** [comment]
42688b7331e2986d4f5b2d5511e3bd243b1a64d3

**Comment by biharygergo** [comment]
b4867ddea93579b462aae9435c3042885d1da515

**Comment by biharygergo** [comment]
c5ca59206d80a0a34185a0dd6a1a8f04d6533bd1

**Comment by biharygergo** [comment]
83082633ec37cc9be4ad3ecb9009577b5e59ec6d

**Comment by biharygergo** [comment]
76af2298a88c20fdab6c4a5f5b24b33161c9d02a

**Comment by biharygergo** [comment]
6f75f79a5ec96116ec21c61146a77ee15fbb3fbb

**Comment by biharygergo** [comment]
9b3f3cc2e5e27bf59e0249e8b14ebe670f161b4c

**Comment by biharygergo** [comment]
081f43038e29def27f4524a349e20bb4e4ad35c8

**Comment by biharygergo** [comment]
528cd6486b052b1cbf834da701a9f1b0dc03f165

**Comment by biharygergo** [comment]
958e97e1298d60ef8527be582be947f1a57ed28f

**Comment by biharygergo** [comment]
This fixes everything, Travis now works properly: 
934beff13fb8c857259ec156605eb4df8587d425

**Comment by deritamas** [comment]
Great work, Travis is set up properly!

**Comment by deritamas** [comment]
Wiki page about this issue:
https://github.com/biharygergo/outlay/wiki/Continuous-integration

**Comment by micskeiz** [comment]
OK
