### ISSUE TITLE
Static analysis with lint

### ISSUE THREAD

**Issue by davidka95** [biharygergo/outlay#6]

**Comment by davidka95** [comment]
21b973a5e030f183933d8c8072c37b12e91c56bd

**Comment by davidka95** [comment]
4204266ab7453346af206c68302d1d3c95c54220

**Comment by davidka95** [comment]
3e2f07d488ece4ba2fa1fa7e053f81f5e2c4838a

**Comment by davidka95** [comment]
9a055e127c27f4cab573122b71647896663a8631

**Comment by davidka95** [comment]
a672350409b44233f994864f6fe5fa99ae3b909b

**Comment by davidka95** [comment]
dc2e7fca77cdb61edb02d9eae4a39cfe9bc50a89

**Comment by davidka95** [comment]
1542e22b01360bcfb89e5b5a7f767609e2432b88

**Comment by davidka95** [comment]
f81db95defc93c26ba1fafe77348e83bfd22c1f4

**Comment by davidka95** [comment]
1fefe8951824af59e520b3e405dfca0a7a3bc843

**Comment by davidka95** [comment]
138e923d01715908b5ee0e4d4d7f18d05e4a5acd

**Comment by davidka95** [comment]
d7f9d9ca06fbd844ea91be8e7a9989c09d0a7ff8

**Comment by davidka95** [comment]
cf674c8df99e84a2d280787ebbcec3ff3a701306

**Comment by deritamas** [comment]
e1af2c444ad98b200c568a7bedb65308ad5ecfd4

**Comment by deritamas** [comment]
3eeed4fbc62774d00159109a4c061e91a6d303b7

**Comment by deritamas** [comment]
f408005c6b393e63e749794dc1b912c1d654d2a0

**Comment by deritamas** [comment]
6d8c75a856ae1b032d8ec5d075ce87bbdd169ec7

**Comment by deritamas** [comment]
8daf21894f9dd0c80dbbd8e3d199ee14972a21ab

**Comment by deritamas** [comment]
010fe3bf169aca6cf0c01b3cffbfeacec72efb44

**Comment by deritamas** [comment]
Made some improvements, @davidka95 please check!

**Comment by davidka95** [comment]
Good job @deritamas ! Travis test correctly!

**Comment by deritamas** [comment]
Wiki page about this issue:
https://github.com/biharygergo/outlay/wiki/Static-code-analysis

**Comment by micskeiz** [comment]
OK
