### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by deritamas** [biharygergo/outlay#7]
Let's test the functions of SonarQube!

**Comment by deritamas** [comment]
386327ab289311f3e022b7818f9dbb0be867fa3a

**Comment by deritamas** [comment]
2978b100d6e12300f4c09175ab3f632d0f3afab7

**Comment by deritamas** [comment]
fc687eb022100309631fd991c39e92593cc2b821

**Comment by deritamas** [comment]
51ef4c8501f29fb3fb07e642cd789b75cfb76e97

**Comment by deritamas** [comment]
@davidka95 please check!

**Comment by deritamas** [comment]
Wiki page about this issue:
https://github.com/biharygergo/outlay/wiki/Static-code-analysis

**Comment by micskeiz** [comment]
OK
